[build-system]
#requires = ["pdm-backend"]
#build-backend = "pdm.backend"
requires = [ "setuptools", "wheel", "setuptools-git-versioning", "pytest-runner"]
build-backend = "setuptools.build_meta"

[project]
name = "faber-bench"
authors = [
  {name = "Stefan Seefeld", email = "stefan@seefeld.name"}
]
maintainers = [
  {name = "Stefan Seefeld", email = "stefan@seefeld.name"}
]
description = "A graphical Faber interface."
requires-python = ">= 3.6"
dependencies = []
dynamic = ["version"]
license = "BSL-1.0"
license-files = ["LICENSE"]
classifiers = ["Environment :: Console",
               "Intended Audience :: Developers",
               "Operating System :: OS Independent",
               "Topic :: Software Development :: Build Tools",
               "Topic :: Software Development :: Testing",
               "Programming Language :: Python"]

[project.urls]
Homepage = "https://stefanseefeld.github.io/faber"
Repository = "https://github.com/stefanseefeld/faber"
Issues = "https://github.com/stefanseefeld/faber/issues"

[project.gui-scripts]
faber-bench = "faber_bench.cli:cli_main"

#[tool.setuptools]
#package-dir = {"" = ".."}
#script-files = []

[tool.setuptools-git-versioning]
enabled = true
version_callback = "setup:get_version_from_git"

[tool.setuptools.packages.find]
#where = ["../src"]
include = ["faber_bench*"]

[tool.setuptools.package-data]
"*" = ["*.ui"]

[tool.setuptools.dynamic]
dependencies = {file = ['requirements.txt']}
